# Generated by Django 3.1.3 on 2020-11-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('number', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=40)),
                ('zip', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('phone', models.IntegerField(default='')),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('product_name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
