# Generated by Django 3.0.8 on 2020-08-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
