# Generated by Django 3.1.3 on 2020-11-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201118_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='updateorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField(default='')),
                ('email', models.CharField(max_length=30)),
                ('updatedesc', models.CharField(max_length=300)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
