# Generated by Django 3.1.3 on 2020-11-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_updateorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateorder',
            name='email',
        ),
    ]
