# Generated by Django 3.1.3 on 2021-05-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_men'),
    ]

    operations = [
        migrations.CreateModel(
            name='women',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('product_name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
